### ISSUE TITLE
Geocoder Search Bar

### ISSUE THREAD

**Issue by jmkiley** [mapbox/mapbox-plugins-ios#14]
An iOS version of the [mapbox-gl-geocoder](https://github.com/mapbox/mapbox-gl-geocoder) would be helpful for developers. Could allow people to more easily incorporate [MapboxGeocoder.swift](https://github.com/mapbox/MapboxGeocoder.swift/).

It would require an additional dependency, so we would need to decide whether we want to [support Carthage](https://github.com/mapbox/mapbox-plugins-ios/issues/10) in this library.

It would likely be a `UISearchBar` with a 4-5 row `UITableView` that pops over the map, and return an array that can be mapped by the user. 

cc @captainbarbosa @1ec5

**Comment by 1ec5** [comment]
It would be nice to keep the concept of map plugins focused to functionality that’s contained in the map itself. The functionality proposed here is akin to how the navigation SDK – as a separate library – vends its own UI that has a map view as its centerpiece. That isn’t really a consideration for mapbox-gl-geocoder, which is designed as an ornament in the map itself, similar to the compass button provided by the iOS SDK.

**Comment by jmkiley** [comment]
Yeah. I think we need to explore whether we want to use the plugins repo to house plugins that solely use the Maps SDK, or to also include plugins intended to bridge the Maps SDK with other other Mapbox libraries (such as geocoding).

**Comment by captainbarbosa** [comment]
>It would be nice to keep the concept of map plugins focused to functionality that’s contained in the map itself

Would it make more sense to include this functionality within [MapboxGeocoder.swift](https://github.com/mapbox/MapboxGeocoder.swift) directly instead?

**Comment by 1ec5** [comment]
Like the other service libraries, MapboxGeocoder.swift is currently designed to be a lightweight wrapper around the Geocoding API proper, akin to the functionality provided by the Mapbox JavaScript SDK. So far it seems that our non-UI libraries are language-oriented (e.g., Swift) whereas the UI libraries are platform-oriented (e.g., iOS).

At the risk of repo proliferation, a separate UI library could depend on MapboxGeocoder.swift as an implementation detail, just as the navigation SDK depends on MapboxDirections.swift as an implementation detail.

**Comment by jmkiley** [comment]
[Android Places Plugin](https://github.com/mapbox/mapbox-plugins-android/tree/master/plugin-places) has landed. I have been working on a search bar with iOS on the side, but am still a little unsure about where it would live. There is also a case for including it as an [example with the MapboxGeocoder.swift](https://github.com/mapbox/MapboxGeocoder.swift/issues/137) library, as @captainbarbosa mentioned.

**Comment by Narek1994** [comment]
Hi, any news about the iOS version of build in search bar?

**Comment by Ahmeddben** [comment]
> [Android Places Plugin](https://github.com/mapbox/mapbox-plugins-android/tree/master/plugin-places) has landed. I have been working on a search bar with iOS on the side, but am still a little unsure about where it would live. There is also a case for including it as an [example with the MapboxGeocoder.swift](https://github.com/mapbox/MapboxGeocoder.swift/issues/137) library, as @captainbarbosa mentioned.

Any update on this?

**Comment by captainbarbosa** [comment]
We currently don't have plan to introduce a geocoder search bar plugin for this repository while we focus on other roadmap priorities. We're considering including a search bar as an integrated component of [MapboxGeocoder.swift](https://github.com/mapbox/MapboxGeocoder.swift/) or at least include an example there, but have no timeline on when this would be implemented.
